### ISSUE TITLE
Convert to maven?

### ISSUE THREAD

**Issue by chrisco484** [Turreta/turreta-jpoller#1]
Would you like a hand converting the project to maven?

**Comment by ksangabriel** [comment]
The codes and libraries are too old. Some code files aren't even remotely related to "polling" - too many unrelated files. I would suggest using Spring Integration instead or use the jpoller as is.

**Comment by chrisco484** [comment]
We have a ban on Spring* :)

 

From our experience with client projects once Spring gets introduced to
a project it ends up on a one way train to 'bloatware' land and needs
much more cloud resources to run it effectively compared to simple POJO
apps that do stuff without all the CPU zapping 'under the hood'
reflection that occurs. Not many devs tend to worry about it though
because most don't ever look under the hood to see how that stuff works
and they aren't the ones paying the massive cloud costs to run it :)

 

________________________________

**Comment by chrisco484** [comment]
I have been in touch with the original developer Cristiano Sadun. He is
pretty busy with other stuff now but I suggested he create an 'official'
JPoller GitHub repo and he has now down this:
https://github.com/crsadun/jpoller

 

I am in the process of importing the current code base from SourceForge
and then I plan to mavenize it and then get it deployed to a public
maven repo so people can simply add it to their pom.xml for inclusion.

 

One issue might be the sadun utils library that it uses - he still has
access to all that as well but maybe we could make a cut down version of
that util library that only includes what is needed by JPoller.

 

I realize that you have opinions on how hard it will be to mavenize but
maybe if we both put out heads together on it we can make it happen.

 

 

________________________________
